'use strict';
// docs/API.md is generated by scripts/gen-api-docs.js (the route list from server/app.js ROUTE_MODULES, and the
// narrative in the script). A hand edit to docs/API.md is lost the next time anyone runs the generator, so it is
// caught here: the file must be exactly what the script writes (`npm run gen-api-docs` after editing the script).
const { test } = require('node:test');
const assert = require('node:assert');
const { spawnSync } = require('node:child_process');
const path = require('node:path');

test('docs/API.md is exactly what scripts/gen-api-docs.js writes', () => {
  const r = spawnSync(process.execPath, ['--no-warnings=ExperimentalWarning', path.join(__dirname, '..', 'scripts', 'gen-api-docs.js'), '--check'],
    { encoding: 'utf8', env: { ...process.env, SUDS_ENV: 'test' }, timeout: 60_000 });
  assert.equal(r.status, 0, `${r.stderr || r.stdout}`);
  assert.match(r.stdout, /up to date/);
});
